### ISSUE TITLE
All arrays in API requests are turned into objects

### ISSUE THREAD

**Issue by matas-valuzis** [auth0/auth0-PHP#540] opened 2021-08-17 12:53 UTC
### SDK Version

8.0.0-BETA2

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

Some requests to Management API are not possible since all arrays are transformed to JSON objects. i.e `addRoles` method fails with error 
```
"statusCode":400,
"error":"Bad Request",
"message":"Payload validation error: 'Expected type array but found type object' on property roles (List of roles IDs to associated with the user).",
"errorCode":"invalid_body"
```

### How can we reproduce this issue?

```php
/**
* @var Management $auth0
*/ 
$auth0->users()->addRoles('123', ['rol_123']);
```

### Additional context

Bug is in `Auth0\SDK\Utility\HttpRequest::withBody` due to `JSON_FORCE_OBJECT` flag
```php
if (is_object($body)) {
    $body = json_encode($body, JSON_FORCE_OBJECT | JSON_THROW_ON_ERROR);
} elseif (is_array($body) || is_string($body) && $jsonEncode === true) {
    $body = json_encode($body, JSON_THROW_ON_ERROR);
}
```
This produces bodies like
```json
"{"roles":{"0":"role_123"}}"
```

**Comment by evansims** [comment] 2021-08-17 18:04
Hey @matas-valuzis 👋 Thanks, let me check on this one and get back to you.

**Comment by evansims** [comment] 2021-08-17 23:35
Thanks for the heads-up on this, @matas-valuzis! I've pushed a fix for this that will be part of BETA3 later this week. I've also added regression tests to ensure this is caught in the future.

**Closed** 2021-08-17 23:34 UTC
Labels: needs investigation

**Comment by gfornari** [comment] 2021-09-02 13:41
Hello @evansims 🙂  My team and me stumbled upon the same issue in `8.0.0-BETA2`, but we were glad to see that it has already been solved 🎉 

Because we're developing along with the new version following its changes, when do you think a `8.0.0-BETA3` of the SDK with these changes will be released? Or, is there a public roadmap I can checkout?

Thank you!

**Comment by gfornari** [comment] 2021-09-02 14:15
Awesome! Thank you very much.
