### ISSUE TITLE
Packagist does not recognize tag v7.3 

### ISSUE THREAD

**Issue by stevef** [auth0/auth0-PHP#454] opened 2020-09-23 16:51 UTC
### Description

While attempting to upgrade auth0-PHP to tag v7.3 in an effort to upgrade to Laravel 8, I noticed composer was not aware of the available tag.

### Reproduction

In composer.json, I updated my requirement to the following:

`"auth0/auth0-php": "^7.3"
`

After running `composer update`, the following error was produced:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package auth0/auth0-php ^7.3 exists as auth0/auth0-php[0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 3.0.0, 3.0.1, 3.1.0, 3.2.0, 3.2.1, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 4.0.0, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1, 5.3.2, 5.4.0, 5.5.0, 5.5.1, 5.6.0, 5.7.0, 6.0.0-alpha.1, 6.0.0-alpha.2, 7.0.0, 7.1.0, 7.2.0, dev-5.x.x-dev, dev-master, dev-test-refactor, dev-update-stalebot-labels] but these are rejected by your constraint.
```

It seems Packagist is not aware of the new 7.3 tag?

**Comment by evansims** [comment] 2020-10-26 19:54
Hi Steve. 👋  This issue appears to be resolved, or I'm otherwise unable to reproduce it on my end, and may have been addressed by the release of 7.4 to Packagist. Please drop a comment here if you or others encounter the problem again.

**Closed by evansims** 2020-10-26 19:54 UTC
Labels: needs investigation
